## Exploratory Data Analysis: _NFL Statistics_

In [1]:
# import dash
# from dash import Dash
# from dash import dcc
# from dash import html
# from dash.dependencies import Input, Output
# import plotly.express as px

import pandas as pd

In [14]:
# Load your NFL player statistics data into a Pandas DataFrame
dataset = pd.read_csv('./data/nfl_offensive_stats.csv')

In [15]:
dataset.tail(1)

,game_id,player_id,position,player,team,pass_cmp,pass_att,pass_yds,pass_td,pass_int,...,OT,Roof,Surface,Temperature,Humidity,Wind_Speed,Vegas_Line,Vegas_Favorite,Over_Under,game_date
19972,202202130cin,WilcMi01,TE,Mitchell Wilcox,CIN,0,0,0,0,0,...,False,dome,matrixturf,72,45,0,-4.0,LAR,48.5,2/13/2022

In [16]:
dataset.columns

Index(['game_id', 'player_id', 'position ', 'player', 'team', 'pass_cmp',
       'pass_att', 'pass_yds', 'pass_td', 'pass_int', 'pass_sacked',
       'pass_sacked_yds', 'pass_long', 'pass_rating', 'rush_att', 'rush_yds',
       'rush_td', 'rush_long', 'targets', 'rec', 'rec_yds', 'rec_td',
       'rec_long', 'fumbles_lost', 'rush_scrambles', 'designed_rush_att',
       'comb_pass_rush_play', 'comb_pass_play', 'comb_rush_play',
       'Team_abbrev', 'Opponent_abbrev', 'two_point_conv', 'total_ret_td',
       'offensive_fumble_recovery_td', 'pass_yds_bonus', 'rush_yds_bonus',
       'rec_yds_bonus', 'Total_DKP', 'Off_DKP', 'Total_FDP', 'Off_FDP',
       'Total_SDP', 'Off_SDP', 'pass_target_yds', 'pass_poor_throws',
       'pass_blitzed', 'pass_hurried', 'rush_yds_before_contact', 'rush_yac',
       'rush_broken_tackles', 'rec_air_yds', 'rec_yac', 'rec_drops', 'offense',
       'off_pct', 'vis_team', 'home_team', 'vis_score', 'home_score', 'OT',
       'Roof', 'Surface', 'Temperature', 'Humidity', 'Wind_Speed',
       'Vegas_Line', 'Vegas_Favorite', 'Over_Under', 'game_date'],
      dtype='object')

### Objective:

Write function that obtains subset of `nfl_offensive_stats.csv` that contains the `game_id`, `player`, and `pass_yds`. 

Isolate segment of subset data where player is **Aaron Rodgers**. 

#### Future Objectives:

Replace `game_id` with **opponent information** (column currently undecided).

In [44]:
def get_player_subset_of_dataset(player: str = "Aaron Rodgers", 
                                 columns_to_isolate: list = ["game_id", "player", "pass_yds"], ):
    PLAYER_NAME_MATCH = (dataset["player"] == player)
    print(f"Player is `{player}`.")
    return dataset[columns_to_isolate][PLAYER_NAME_MATCH]

In [45]:
subset = get_player_subset_of_dataset().drop(columns=["player"])

subset

Player is `Aaron Rodgers`.

            game_id  pass_yds
0      201909050chi       203
510    201909150gnb       209
904    201909220gnb       235
1156   201909260gnb       422
1554   201910060dal       238
2157   201910140gnb       283
2381   201910200gnb       429
2714   201910270kan       305
3133   201911030sdg       161
3349   201911100gnb       233
4111   201911240sfo       104
4457   201912010nyg       243
4704   201912080gnb       195
5084   201912150gnb       203
5681   201912230min       216
5830   201912290det       323
6244   202001120gnb       243
6305   202001190sfo       326
6513   202009130min       364
6865   202009200gnb       240
7326   202009270nor       283
7860   202010050gnb       327
8508   202010180tam       160
8709   202010250htx       283
9125   202011010gnb       291
9271   202011050sfo       305
9759   202011150gnb       325
10045  202011220clt       311
10486  202011290gnb       211
10784  202012060gnb       295
11188  202012130det       290
11518  202012190gnb       143
12001  202012270gnb       231
12317  202101030chi       240
12823  202101160gnb       296
12892  202101240gnb       346
13178  202109120nor       133
13724  202109200gnb       255
14091  202109260sfo       261
14301  202110030gnb       248
14615  202110100cin       344
14988  202110170chi       195
15333  202110240gnb       274
15607  202110280crd       184
16457  202111140gnb       292
16849  202111210min       385
17195  202111280gnb       307
17888  202112120gnb       341
18328  202112190rav       268
18545  202112250gnb       202
19014  202201020gnb       288
19427  202201090det       138
19828  202201220gnb       225